/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Geocode a place name or address
         * @description Turns a place name or address into coordinates. Results are ranked: exact name matches first, then names that start with the query, then names containing every word of the query. An empty `results` array means nothing matched; it is not an error.
         */
        get: operations["geocode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reverse-geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find the address at a coordinate
         * @description Turns a latitude/longitude into the nearest meaningful location: an address if one is close, otherwise a named place, otherwise the nearest named street (`match_type` tells you which). Returns 404 when nothing is found within 2 km.
         */
        get: operations["reverseGeocode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calculate a route between two points
         * @description Returns the fastest route for the chosen travel mode, with its distance, estimated travel time and a GeoJSON LineString. Origin and destination are snapped to the nearest road the mode can use; the snapped points are returned in `waypoints`.
         */
        get: operations["route"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Address */
        Address: {
            /**
             * Formatted
             * @example Sukhbaatar Square, Ulaanbaatar, Mongolia
             */
            formatted: string;
            /**
             * Name
             * @description Building, place or street name.
             */
            name?: string | null;
            /** House Number */
            house_number?: string | null;
            /** Street */
            street?: string | null;
            /**
             * Neighborhood
             * @description Sub-district, for example a khoroo (хороо).
             */
            neighborhood?: string | null;
            /** District */
            district?: string | null;
            /** City */
            city?: string | null;
            /** Country */
            country?: string | null;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /**
             * Code
             * @description Stable, machine-readable error code.
             * @enum {string}
             */
            code: "INVALID_REQUEST" | "INVALID_API_KEY" | "API_KEY_REVOKED" | "ENDPOINT_NOT_ALLOWED" | "NOT_FOUND" | "REQUEST_TIMEOUT" | "RATE_LIMIT_EXCEEDED" | "INTERNAL_ERROR" | "UPSTREAM_ERROR" | "SERVICE_UNAVAILABLE";
            /**
             * Message
             * @description Human-readable explanation. Wording may change; do not parse it.
             */
            message: string;
            /**
             * Details
             * @description Optional structured context, for example the offending `field`.
             */
            details?: {
                [key: string]: unknown;
            } | null;
            /**
             * Request Id
             * @description Identifies this request in the server logs (same as the `X-Request-ID` header). Quote it when you contact support.
             */
            request_id?: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** GeocodeResponse */
        GeocodeResponse: {
            /**
             * Query
             * @example Sukhbaatar Square
             */
            query: string;
            /** Results */
            results: components["schemas"]["GeocodeResult"][];
            /**
             * Count
             * @description Number of results returned.
             * @example 1
             */
            count: number;
        };
        /** GeocodeResult */
        GeocodeResult: {
            /**
             * Id
             * @description Opaque, stable identifier of the place.
             * @example plc_123
             */
            id: string;
            /**
             * Name
             * @example Sukhbaatar Square
             */
            name: string;
            /**
             * Address
             * @example Ulaanbaatar, Mongolia
             */
            address?: string | null;
            /**
             * Latitude
             * @example 47.9184
             */
            latitude: number;
            /**
             * Longitude
             * @example 106.9177
             */
            longitude: number;
            /**
             * Type
             * @description Place category, for example `landmark` or `district`.
             * @example place
             */
            type: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** LineString */
        LineString: {
            /**
             * Type
             * @default LineString
             * @constant
             */
            type: "LineString";
            /**
             * Coordinates
             * @description GeoJSON positions as `[longitude, latitude]` pairs.
             * @example [
             *       [
             *         106.9177,
             *         47.9184
             *       ],
             *       [
             *         106.9057,
             *         47.922
             *       ]
             *     ]
             */
            coordinates: [
                number,
                number
            ][];
        };
        /** Location */
        Location: {
            /**
             * Latitude
             * @example 47.9184
             */
            latitude: number;
            /**
             * Longitude
             * @example 106.9177
             */
            longitude: number;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "unavailable";
            /** Checks */
            checks: {
                [key: string]: "ok" | "fail" | "not_configured";
            };
        };
        /** ReverseGeocodeResponse */
        ReverseGeocodeResponse: {
            /** @description The coordinates that were requested. */
            location: components["schemas"]["Location"];
            address: components["schemas"]["Address"];
            /**
             * Match Type
             * @description What kind of feature the address was derived from.
             * @enum {string}
             */
            match_type: "address" | "place" | "street";
            /**
             * Distance Meters
             * @description Distance from the requested point to the match.
             * @example 12.4
             */
            distance_meters: number;
        };
        /** Route */
        Route: {
            /**
             * Distance Meters
             * @example 4200
             */
            distance_meters: number;
            /**
             * Duration Seconds
             * @example 620
             */
            duration_seconds: number;
            geometry: components["schemas"]["LineString"];
        };
        /** RouteResponse */
        RouteResponse: {
            route: components["schemas"]["Route"];
            mode: components["schemas"]["TravelMode"];
            /**
             * Waypoints
             * @description Snapped origin and destination, in that order.
             */
            waypoints: components["schemas"]["Waypoint"][];
        };
        /**
         * TravelMode
         * @enum {string}
         */
        TravelMode: "driving" | "walking";
        /** Waypoint */
        Waypoint: {
            /** @description The coordinate you sent. */
            input: components["schemas"]["Location"];
            /** @description The point on the road network the route starts or ends at. */
            location: components["schemas"]["Location"];
            /**
             * Snap Distance Meters
             * @description Distance between `input` and `location`.
             */
            snap_distance_meters: number;
            /**
             * Name
             * @description Name of the road at the snapped location.
             */
            name?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    geocode: {
        parameters: {
            query: {
                /** @description Place name or address to search for. Latin and Cyrillic are both supported. */
                q: string;
                /** @description Maximum number of results. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeResponse"];
                };
            };
            /** @description 400 INVALID_REQUEST */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_REQUEST",
                     *         "message": "Invalid value for 'lat': must be between -90 and 90.",
                     *         "details": {
                     *           "field": "lat"
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 401 INVALID_API_KEY */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_API_KEY",
                     *         "message": "The API key is missing or invalid."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 403 API_KEY_REVOKED or ENDPOINT_NOT_ALLOWED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "API_KEY_REVOKED",
                     *         "message": "This API key has been revoked."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 408 REQUEST_TIMEOUT */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "REQUEST_TIMEOUT",
                     *         "message": "The data service did not respond in time."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 429 RATE_LIMIT_EXCEEDED */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "RATE_LIMIT_EXCEEDED",
                     *         "message": "Too many requests."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 500 INTERNAL_ERROR */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INTERNAL_ERROR",
                     *         "message": "Internal server error."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 502 UPSTREAM_ERROR */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "UPSTREAM_ERROR",
                     *         "message": "The upstream data service returned an error."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 503 SERVICE_UNAVAILABLE */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "SERVICE_UNAVAILABLE",
                     *         "message": "The service is temporarily unavailable."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reverseGeocode: {
        parameters: {
            query: {
                /** @description Latitude in decimal degrees (WGS84). */
                lat: number;
                /** @description Longitude in decimal degrees (WGS84). */
                lon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReverseGeocodeResponse"];
                };
            };
            /** @description 400 INVALID_REQUEST */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_REQUEST",
                     *         "message": "Invalid value for 'lat': must be between -90 and 90.",
                     *         "details": {
                     *           "field": "lat"
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 401 INVALID_API_KEY */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_API_KEY",
                     *         "message": "The API key is missing or invalid."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 403 API_KEY_REVOKED or ENDPOINT_NOT_ALLOWED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "API_KEY_REVOKED",
                     *         "message": "This API key has been revoked."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 404 NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "NOT_FOUND",
                     *         "message": "No result was found for this request."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 408 REQUEST_TIMEOUT */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "REQUEST_TIMEOUT",
                     *         "message": "The data service did not respond in time."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 429 RATE_LIMIT_EXCEEDED */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "RATE_LIMIT_EXCEEDED",
                     *         "message": "Too many requests."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 500 INTERNAL_ERROR */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INTERNAL_ERROR",
                     *         "message": "Internal server error."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 502 UPSTREAM_ERROR */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "UPSTREAM_ERROR",
                     *         "message": "The upstream data service returned an error."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 503 SERVICE_UNAVAILABLE */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "SERVICE_UNAVAILABLE",
                     *         "message": "The service is temporarily unavailable."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    route: {
        parameters: {
            query: {
                /** @description Longitude and latitude separated by a comma, in that order (GeoJSON order). */
                origin: string;
                /** @description Longitude and latitude separated by a comma, in that order (GeoJSON order). */
                destination: string;
                /** @description Travel mode. */
                mode?: components["schemas"]["TravelMode"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponse"];
                };
            };
            /** @description 400 INVALID_REQUEST */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_REQUEST",
                     *         "message": "Invalid value for 'lat': must be between -90 and 90.",
                     *         "details": {
                     *           "field": "lat"
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 401 INVALID_API_KEY */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_API_KEY",
                     *         "message": "The API key is missing or invalid."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 403 API_KEY_REVOKED or ENDPOINT_NOT_ALLOWED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "API_KEY_REVOKED",
                     *         "message": "This API key has been revoked."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 404 NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "NOT_FOUND",
                     *         "message": "No result was found for this request."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 408 REQUEST_TIMEOUT */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "REQUEST_TIMEOUT",
                     *         "message": "The data service did not respond in time."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 429 RATE_LIMIT_EXCEEDED */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "RATE_LIMIT_EXCEEDED",
                     *         "message": "Too many requests."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 500 INTERNAL_ERROR */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INTERNAL_ERROR",
                     *         "message": "Internal server error."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 502 UPSTREAM_ERROR */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "UPSTREAM_ERROR",
                     *         "message": "The upstream data service returned an error."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 503 SERVICE_UNAVAILABLE */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "SERVICE_UNAVAILABLE",
                     *         "message": "The service is temporarily unavailable."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description A required dependency is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
